//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toopeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Groups = new HashSet<Group>();
            this.Group_Contact = new HashSet<Group_Contact>();
            this.Messages = new HashSet<Message>();
        }
    
        public string userName { get; set; }
        public string numberPhone { get; set; }
        public string email { get; set; }
        public string avatarUrl { get; set; }
        public Nullable<byte> Presence { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public System.Data.Entity.Spatial.DbGeography position { get; set; }
        public Nullable<byte> sex { get; set; }
        public Nullable<byte> age { get; set; }
        public Nullable<System.DateTime> nearbySearch { get; set; }
    
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Group_Contact> Group_Contact { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
