//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toopeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Group_Contact = new HashSet<Group_Contact>();
            this.Messages = new HashSet<Message>();
        }
    
        public string groupName { get; set; }
        public string subject { get; set; }
        public Nullable<byte> type { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string fk_ContactCretor { get; set; }
        public System.Data.Entity.Spatial.DbGeography position { get; set; }
        public string fk_parentName { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual ICollection<Group_Contact> Group_Contact { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
