//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toopeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Contact
    {
        public int id { get; set; }
        public string Fk_Contact { get; set; }
        public string fkGroup { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<byte> levelAccess { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Group Group { get; set; }
    }
}
