//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toopeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public string id { get; set; }
        public byte type { get; set; }
        public string url { get; set; }
        public string text { get; set; }
        public string fk_Contact_sender { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string fkGroup { get; set; }
        public string fk_Contact_receiver { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Group Group { get; set; }
    }
}
