//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToopetoServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int id { get; set; }
        public Nullable<byte> type { get; set; }
        public string url { get; set; }
        public string text { get; set; }
        public Nullable<int> EntityR_fk { get; set; }
    
        public virtual EntityR EntityR { get; set; }
    }
}
