//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToopetoServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_User
    {
        public int id { get; set; }
        public Nullable<int> Fk_Room { get; set; }
        public Nullable<int> Fk_User { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
