//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToopetoServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.friends = new HashSet<friend>();
            this.friends1 = new HashSet<friend>();
            this.Room_User = new HashSet<Room_User>();
        }
    
        public int id { get; set; }
        public string userName { get; set; }
    
        public virtual EntityR EntityR { get; set; }
        public virtual ICollection<friend> friends { get; set; }
        public virtual ICollection<friend> friends1 { get; set; }
        public virtual ICollection<Room_User> Room_User { get; set; }
    }
}
